// Predefined technology stack for tutors
export const TECH_STACK = {
  'Frontend': [
    'React',
    'Vue',
    'Angular',
    'Next.js',
    'Svelte',
    'TypeScript',
    'JavaScript',
    'HTML/CSS',
    'Tailwind',
    'Astro',
  ],
  'Backend': [
    'Node.js',
    'Python',
    'Django',
    'FastAPI',
    'Go',
    'Rust',
    'Java',
    'C#/.NET',
    'PHP',
    'Ruby on Rails',
    'Spring Boot',
  ],
  'Mobile': [
    'React Native',
    'Flutter',
    'Swift',
    'Kotlin',
    'Xamarin',
  ],
  'Cloud Providers': [
    'AWS',
    'Google Cloud',
    'Azure',
    'DigitalOcean',
    'Heroku',
    'Vercel',
    'Netlify',
  ],
  'DevOps & Infrastructure': [
    'Docker',
    'Kubernetes',
    'GitHub Actions',
    'CI/CD',
    'Terraform',
    'Linux',
  ],
  'Databases': [
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Firebase',
    'Supabase',
    'DynamoDB',
  ],
  'AI & LLMs': [
    'ChatGPT',
    'Claude',
    'Gemini',
    'LLaMA',
    'Prompt Engineering',
    'RAG (Retrieval-Augmented Generation)',
    'Fine-tuning',
  ],
  'Other': [
    'GraphQL',
    'REST API',
    'Git/GitHub',
    'Testing (Jest, Vitest)',
    'Design Systems',
    'Web3/Blockchain',
  ],
} as const

// Flat list for easier searching
export const ALL_TECHS = Object.values(TECH_STACK).flat().sort()
